name: hotels
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  dio: ^5.7.0
  retrofit: ^4.4.1
  get_it: ^8.0.2
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  dots_indicator: ^3.0.0
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4

flutter:
  uses-material-design: true
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.otf
        - asset: fonts/SF-Pro-Display-Light.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
        - asset: fonts/SF-Pro-Display-Regular.otf
  assets:
    - assets/icons/
    - assets/images/